// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkfsmIVGM_G1rHfllihz5FvF1TAuOudgk',
    appId: '1:577291341581:web:cf55e362dcf08af400aa44',
    messagingSenderId: '577291341581',
    projectId: 'cavi-nguyendevelop',
    authDomain: 'cavi-nguyendevelop.firebaseapp.com',
    storageBucket: 'cavi-nguyendevelop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_sW9gUQAth_0YwBFhMdY8smRk1yRSy-4',
    appId: '1:577291341581:android:cea97e2e06c2f17200aa44',
    messagingSenderId: '577291341581',
    projectId: 'cavi-nguyendevelop',
    storageBucket: 'cavi-nguyendevelop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWR-rEGaLsXpWytpQtnLW0IS5OGY1EiQw',
    appId: '1:577291341581:ios:c4e859189cd126b100aa44',
    messagingSenderId: '577291341581',
    projectId: 'cavi-nguyendevelop',
    storageBucket: 'cavi-nguyendevelop.appspot.com',
    androidClientId: '577291341581-h5fmaf3u6aa9338u09qs1mmj0kpgtuvd.apps.googleusercontent.com',
    iosClientId: '577291341581-dksksm9d06flrnb6lrh3msbn9o3b7tvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.caviapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWR-rEGaLsXpWytpQtnLW0IS5OGY1EiQw',
    appId: '1:577291341581:ios:388da31711e451fb00aa44',
    messagingSenderId: '577291341581',
    projectId: 'cavi-nguyendevelop',
    storageBucket: 'cavi-nguyendevelop.appspot.com',
    androidClientId: '577291341581-h5fmaf3u6aa9338u09qs1mmj0kpgtuvd.apps.googleusercontent.com',
    iosClientId: '577291341581-ajpoi1aujfqa876a06vilt4ohj3p2665.apps.googleusercontent.com',
    iosBundleId: 'com.example.caviapp.RunnerTests',
  );
}
