// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGJIdJGTyDAkRrioEuTxUHAzDfp1SvQo',
    appId: '1:531312460319:web:0d1027d26a25ab4f8e0b2a',
    messagingSenderId: '531312460319',
    projectId: 'cavi-1433e',
    authDomain: 'cavi-1433e.firebaseapp.com',
    storageBucket: 'cavi-1433e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZ916A-HpbAbxULYihh674LaKKh4fAHQ',
    appId: '1:531312460319:android:ffea963693e4e5bb8e0b2a',
    messagingSenderId: '531312460319',
    projectId: 'cavi-1433e',
    storageBucket: 'cavi-1433e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMiQOZRkLSuZQANj4YkZK3SlCHm9pVYI',
    appId: '1:531312460319:ios:baf9b816a04037898e0b2a',
    messagingSenderId: '531312460319',
    projectId: 'cavi-1433e',
    storageBucket: 'cavi-1433e.appspot.com',
    iosClientId: '531312460319-ian1q2m3jll1plg12793k1hns2sig4r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.caviApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdMiQOZRkLSuZQANj4YkZK3SlCHm9pVYI',
    appId: '1:531312460319:ios:baf9b816a04037898e0b2a',
    messagingSenderId: '531312460319',
    projectId: 'cavi-1433e',
    storageBucket: 'cavi-1433e.appspot.com',
    iosClientId: '531312460319-ian1q2m3jll1plg12793k1hns2sig4r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.caviApp',
  );
}
